name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pizzapassword
          MYSQL_DATABASE: pizza
          MYSQL_USER: pizza_user
          MYSQL_PASSWORD: pizzapassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout backend service
        uses: actions/checkout@v4
        with:
          repository: KadenK/jwt-pizza-service
          path: backend

      - name: Create backend config
        run: |
          cd backend
          cat > src/config.js << EOF
          module.exports = {
            jwtSecret: "ci-jwt-secret",
            db: {
              connection: {
                host: "localhost",
                user: "pizza_user",
                password: "pizzapassword",
                database: "pizza",
                connectTimeout: 60000,
              },
              listPerPage: 10,
            },
            factory: {
              url: "https://pizza-factory.cs329.click",
              apiKey: "${{ secrets.FACTORY_API_KEY }}",
            },
          };
          EOF

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: set version
        id: set_version
        run: |
          version=$(date +'%Y%m%d.%H%M%S')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          printf '{"version": "%s" }' "$version" > public/version.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Start backend service
        run: |
          cd backend
          npm run start &
          sleep 10

      - name: Generate pizza data
        run: |
          cd backend
          chmod +x generatePizzaData.sh
          ./generatePizzaData.sh http://localhost:3000

      - name: Build
        run: |
          npm ci && npm run build

      - name: Run tests
        run: |
          npx playwright install --with-deps chromium
          npm run test:coverage

      - name: Update coverage
        run: |
          coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
          curl -s -X POST "https://pizza-factory.cs329.click/api/badge/${{ secrets.NET_ID }}/jwtpizzacoverage?label=Coverage&value=$coverage%25&color=$color" -H "authorization: bearer ${{ secrets.FACTORY_API_KEY }}"

      - name: Update dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/
  deploy:
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    env:
      version: ${{needs.build.outputs.version}}
    steps:
      - name: Create OIDC token to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.CI_IAM_ROLE }}

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: dist/

      - name: Push to AWS S3
        run: |
          echo Deploying $version
          aws s3 cp dist s3://${{ secrets.APP_BUCKET }} --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
